sudo: false
language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

install:
  - mvn clean install -DskipTests
script:
  - mvn clean test

notifications:
  email: false

branches:
  only:
    - master

